version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE=pro
    entrypoint:
      [
        "./start.sh"
      ]
    command: [ "/app/main" ]